/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/ubuntu/Projetc_PGL/scrape_and_save.py': [Errno 2] No such file or directory
